# Bar, wallpaper
exec-once = sleep 1 && dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP # Some fix idk
exec-once = noctalia-shell &

# Input method
# exec-once = fcitx5

# Core components (authentication, lock screen, notification daemon)
exec-once = gnome-keyring-daemon --start --components=secrets
# exec-once = hypridle
exec-once = dbus-update-activation-environment --all
exec-once = /usr/lib/pam_kwallet_init
exec-once = kwalletd6


# Audio
exec-once = easyeffects --hide-window --service-mode

# Cursor
exec-once = hyprctl setcursor MacOS-hyprcursor 24

exec = pkill kded6

exec-once = timeout 10 bash -c 'while ! noctalia-shell ipc call lockScreen lock; do sleep 0.1; done'
