# This file sources other files in `hyprland` and `custom` folders
# You wanna add your stuff in files in `custom`

# debug {
#     disable_logs = false
#     enable_stdout_logs = true
# }在

$qsConfig = noctalia-shell

$ipc = noctalia-shell ipc call

exec = hyprctl dispatch submap global # DO NOT REMOVE THIS OR YOU WON'T BE ABLE TO USE ANY KEYBIND
submap = global # This is required for catchall to work

# Defaults
source=hyprland/env.conf
source=hyprland/execs.conf
source=hyprland/general.conf
source=hyprland/rules.conf
source=~/.cache/hypr/hyprland-colors.conf
source=hyprland/keybinds.conf

# Custom
source=custom/env.conf
source=custom/execs.conf
source=custom/general.conf
source=custom/rules.conf
source=custom/keybinds.conf

# nwg-displays support
source=workspaces.conf
source=monitors.conf