# 我们不打算使用 HyprLang
# 这是一个降级配置，供旧版本 Hyprland 使用

monitor=,preferred,auto,auto

bind = Super, Enter, exec, kitty
bind = Super, Q, killactive,
bind = Super, M, exec, hyprctl dispatch exit

exec = hyprctl notify 3 60000 0 "该 Hyprland 已经过时。请使用 Hyprland 0.55.0 及以上版本"
exec = hyprctl notify 2 60000 0 "使用 Super+Enter 打开 Kitty，使用 Super+Q 退出程序，使用 Super+M 退出 Hyprland"